### PR TITLE
tech(component/footer): add shared footer component

### LINKED ISSUE #21: Add Footer component
Parent ID: #9

### PR DESCRIPTION
**Pull request by shangan23**
## Issue ID #21 
Fixes #21 

## Summary
Created a shared Footer component for the application and which will be organized inside the Shared module under the shared folder.

## Steps to do this Tech Update

angular-cli

```
ng g c shared/footer
```
```
CREATE src/app/shared/footer/footer.component.scss (0 bytes)
CREATE src/app/shared/footer/footer.component.html (21 bytes)
CREATE src/app/shared/footer/footer.component.spec.ts (626 bytes)
CREATE src/app/shared/footer/footer.component.ts (276 bytes)
UPDATE src/app/shared/shared.module.ts (276 bytes)
```
To provide access to the app module add the component into the 'exports' array of the SharedModule decorator
```js
 exports:[
    FooterComponent
  ]
```
To access from the app module include SharedModule to import an array of `AppModule` decorator
```js
  imports: [
     ....
    SharedModule
  ],
```
## Checklist

- [x] Have you added the summary of what your changes do and why you'd like us to include them?
- [x] Have you added the steps you followed?
- [ ] Have the files been linted and formatted?
- [x] Have the docs been updated to match the changes in the PR?
- [ ] Have the tests been updated to match the changes in the PR?
- [ ] Have you run the tests locally to confirm they pass?

### What is the need for this tech update, and the steps to reproduce the issue?
To organize the components inside the Shared module under the shared folder.

### What is the current status?
Created a component and yet to work on the UI

### How does this PR fix the problem, Screenshot Please?
image

### CODE REVIEW

**Comment by naveenvignesh5** [comment]
Squash the two commits to a single one.

**Comment by shangan23** [comment]
> Squash the two commits to a single one.

@naveenvignesh5 - Two commits serve different purposes, one is for creating a component and the other is for associating it with the main app component and module.

**Comment by ramsunvtech** [comment]
@shangan23 resolve merge conflict

**Comment by shangan23** [comment]
> @shangan23 resolve merge conflict

@jpukg @shangan23 - Resolved conflicts

**Pull request merged**
